# ----------------------------------------------------------------------
# Copyright (c) 2021, 2022 Oracle and/or its affiliates. All rights reserved.
# The Universal Permissive License (UPL), Version 1.0
# ----------------------------------------------------------------------

- op: add
  path: /spec/template/spec/imagePullSecrets
  value:
    - name: ocirsecret